//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hausarbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aufgabenstellung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aufgabenstellung()
        {
            this.Rueckmeldung = new HashSet<Rueckmeldung>();
        }
    
        public int AGS_id { get; set; }
        public int Inhalt_id { get; set; }
        public string AGS_Text { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rueckmeldung> Rueckmeldung { get; set; }
        public virtual Inhalt Inhalt { get; set; }
    }
}
