//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hausarbeit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hausarbeit_ENEntitie : DbContext
    {
        public hausarbeit_ENEntitie()
            : base("name=hausarbeit_ENEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aufgabenstellung> Aufgabenstellung { get; set; }
        public virtual DbSet<Inhalt> Inhalt { get; set; }
        public virtual DbSet<Kapitel> Kapitel { get; set; }
        public virtual DbSet<Rueckmeldung> Rueckmeldung { get; set; }
    }
}
