//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hausarbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inhalt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inhalt()
        {
            this.Aufgabenstellung = new HashSet<Aufgabenstellung>();
        }
    
        public int Inhalt_id { get; set; }
        public int Kapitel_id { get; set; }
        public string Inhalt_Text { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aufgabenstellung> Aufgabenstellung { get; set; }
        public virtual Kapitel Kapitel { get; set; }
    }
}
