//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hausarbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rueckmeldung
    {
        public int Rueck_id { get; set; }
        public string Rueck_Text { get; set; }
        public Nullable<int> AGS_id { get; set; }
    
        public virtual Aufgabenstellung Aufgabenstellung { get; set; }
    }
}
